apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f2j9c6mmc-dotnet-basic 
  janus-idp.io/tekton: f2j9c6mmc-dotnet-basic
  backstage.io/kubernetes-id: f2j9c6mmc-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f2j9c6mmc-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  